### ISSUE TITLE
vue-tabevents.es.js?692c:37 Uncaught TypeError: Vue.IsJsonString is not a function

### ISSUE THREAD

**Issue by faizworks** [Almoullim/vue-tabevents#1]
![image](https://user-images.githubusercontent.com/17539113/92742054-af4f2680-f398-11ea-971a-972d472c15dd.png)

**Comment by emanuelceriana** [comment]
The solution is changing line 33 Vue.IsJsonString => Vue.prototype.$IsJsonString

![image](https://user-images.githubusercontent.com/38806235/115162869-5822da00-a07c-11eb-82ae-ad8b1a9456d3.png)

**Comment by bean5** [comment]
See https://github.com/Almoullim/vue-tabevents/pull/2

**Comment by Almoullim** [comment]
fixed in https://github.com/Almoullim/vue-tabevents/pull/2
